challenge:
  address: "192.168.0.108:8000"
  #address: "www.baidu.com:80"
  #address: "122.51.50.72:9999"
  flag_regex: "flag{.+}"
  #flag_regex: "flagProxy"
server:
  url: "http://localhost:8080"
  challenge_id : "abcdefghijk"
  key: "testkeyforchallenge0"
log:
  path: "/tmp/flagProxy.log"